vich_uploader:
    db_driver: orm

    mappings:
        trip_image:
            uri_prefix: /images/trips
            upload_destination: '%kernel.project_dir%/public/images/trips'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
        
        user_image:
            uri_prefix: /images/users
            upload_destination: '%kernel.project_dir%/public/images/users'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
        
        ad_image:
            uri_prefix: /images/ads
            upload_destination: '%kernel.project_dir%/public/images/ads'
            namer: Vich\UploaderBundle\Naming\UniqidNamer