vich_uploader:
    db_driver: orm

    mappings:
        trip_image:
            uri_prefix: /images/trips
            upload_destination: '%kernel.project_dir%/public/images/trips'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
